services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules
      - type: bind
        source: .
        target: /app
        read_only: true

volumes:
  node_modules: