name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t react-test -f Dockerfile.dev .
    - name: Create the Docker container and run the test
      run: docker run -e CI=true react-test npm test
